import { useEffect, useRef, useState, type CSSProperties } from 'react'
import type { ThemeMode } from '../theme'
import darkPoster from '../assets/backdrop/loop-dark.jpg'
import darkLoop from '../assets/backdrop/loop-dark.mp4'
import lightPoster from '../assets/backdrop/loop-light.jpg'
import lightLoop from '../assets/backdrop/loop-light.mp4'

/**
 * The looping film behind everything.
 *
 * Layer order (inside #root, which is `isolation: isolate` — set in theme.ts):
 *   -1  this component  ← gradient base, then poster, then video
 *    0  the R3F canvas (transparent background)
 *    1  the DOM story
 *    2  GrainOverlay
 *   20+ chrome (dots, toggles, progress bar)
 *
 * Both films are mounted at once and cross-faded on theme change; the inactive
 * one is paused, so only one is ever decoding. Each is ~175 KB, so holding both
 * costs less than a single mid-size hero image.
 *
 * The film is skipped entirely — poster still only — under reduced motion, on
 * phones, and on metered connections. That is deliberately the SAME visual
 * (frame 0 of the film), so the fallback is a calmer version of the design
 * rather than a different design.
 *
 * Footage is generated by `scripts/make-backdrop.cjs` from the palettes in
 * theme.ts. Re-run it after changing colours.
 */

// --- treatment ------------------------------------------------------------
// The source is already soft, so this is a light touch. Blur is kept well
// under the ~20px mark where compositing gets expensive (Safari especially);
// its job is only to melt the four colour fields into one continuous wash and
// to hide h264 blocking in the darkest areas.
const BLUR_PX = 7
// Scale past the viewport so the blur's transparent edge never shows.
const SCALE = 1.08
const SATURATE = 1.15
const FADE_MS = 900

const films: Record<ThemeMode, { src: string; poster: string }> = {
	dark: { src: darkLoop, poster: darkPoster },
	light: { src: lightLoop, poster: lightPoster },
}

/** Motion is off, or the connection/device says don't spend bytes on it. */
function useFilmEnabled(reduced: boolean): boolean {
	const [enabled] = useState(() => {
		if (reduced) return false
		if (typeof window === 'undefined') return false
		if (window.matchMedia('(max-width: 767px)').matches) return false
		// Not in every browser; treat absence as "no opinion", not as "yes".
		const conn = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection
		if (conn?.saveData) return false
		return true
	})
	return enabled
}

const layer: CSSProperties = {
	position: 'fixed',
	inset: 0,
	pointerEvents: 'none',
}

function Film({ mode, active }: { mode: ThemeMode; active: boolean }) {
	const ref = useRef<HTMLVideoElement>(null)
	const [ready, setReady] = useState(false)
	const film = films[mode]

	// Only the on-screen film decodes. Pausing the other one (and everything
	// when the tab is hidden) is the difference between a backdrop that costs
	// nothing in the background and one that quietly drains a laptop.
	useEffect(() => {
		const el = ref.current
		if (!el) return
		const sync = () => {
			const shouldPlay = active && !document.hidden
			if (shouldPlay) void el.play().catch(() => {})
			else el.pause()
		}
		sync()
		document.addEventListener('visibilitychange', sync)
		return () => document.removeEventListener('visibilitychange', sync)
	}, [active])

	return (
		<video
			ref={ref}
			aria-hidden
			muted
			loop
			playsInline
			preload="auto"
			poster={film.poster}
			onCanPlay={() => setReady(true)}
			style={{
				...layer,
				width: '100%',
				height: '100%',
				objectFit: 'cover',
				// Never animate from nothing: the poster underneath is already
				// showing the same frame, so this only ever cross-fades detail in.
				opacity: active && ready ? 1 : 0,
				transition: `opacity ${FADE_MS}ms ease`,
				transform: `scale(${SCALE})`,
				filter: `blur(${BLUR_PX}px) saturate(${SATURATE})`,
				willChange: 'opacity',
			}}
		>
			<source src={film.src} type="video/mp4" />
		</video>
	)
}

export function VideoBackdrop({ mode, reduced }: { mode: ThemeMode; reduced: boolean }) {
	const filmEnabled = useFilmEnabled(reduced)
	const poster = films[mode].poster

	return (
		<div aria-hidden style={{ ...layer, zIndex: -1, overflow: 'hidden' }}>
			{/* Base gradient — the original painterly background. Guarantees a
			    designed surface even if the poster 404s or the video never loads. */}
			<div style={{ ...layer, background: 'var(--painter-bg)', transition: 'background 300ms ease' }} />

			{/* Poster still. Also the reduced-motion / mobile / save-data end state. */}
			<div
				style={{
					...layer,
					backgroundImage: `url(${poster})`,
					backgroundSize: 'cover',
					backgroundPosition: 'center',
					transform: `scale(${SCALE})`,
					filter: `blur(${BLUR_PX}px) saturate(${SATURATE})`,
				}}
			/>

			{filmEnabled && (
				<>
					<Film mode="dark" active={mode === 'dark'} />
					<Film mode="light" active={mode === 'light'} />
				</>
			)}

			{/* No scrim here on purpose. The film already carries a per-theme
			    vignette baked in by the generator, and SceneShell paints its own
			    scrim above the 3D layer, directly under the text. A third
			    full-screen layer would crush the edges to black and cost another
			    composite for contrast that is already handled twice. */}
		</div>
	)
}
